#!/usr/bin/env bash

# Ensure Nginx is installed and configured to listen on port 80
apt-get update
apt-get install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart