#!/usr/bin/env bash
# this code changes the following domain resolve ips
# the localhost start from 127.0.0.1 to 127.0.0.2

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
